name: Upload Local Database

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Upload database artifact
        uses: actions/upload-artifact@v5
        with:
          name: inbox-cleaner-state
          path: ./data/state.sqlite
          retention-days: 90
          overwrite: true
